name: Run tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: run tests on ${{ matrix.os }} + Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ['3.8', '3.9', '3.10', '3.11', '3.12']

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }} 

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: System information
        run: python -c "import sys, platform; print(sys.platform, platform.machine())"

      - name: Update pip
        run: python -m pip install -U pip

      - name: Install the package
        run: python -m pip install .[test]

      - name: Run tests
        run: coverage run -m pymnet.tests

      - name: Generate coverage report
        run: coverage xml -o coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: OS,PYTHON
          slug: mnets/pymnet
